//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReloadWS.DAL.Persistencia
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReloadEntities : DbContext
    {
        public ReloadEntities()
            : base("name=ReloadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_CAPTCHAS> TBL_CAPTCHAS { get; set; }
        public virtual DbSet<TBL_CATEGORIAS> TBL_CATEGORIAS { get; set; }
        public virtual DbSet<TBL_MENSAJE_RESPUESTAS> TBL_MENSAJE_RESPUESTAS { get; set; }
        public virtual DbSet<TBL_MENSAJES> TBL_MENSAJES { get; set; }
        public virtual DbSet<TBL_PAISES> TBL_PAISES { get; set; }
        public virtual DbSet<TBL_POST_COMENTARIO_RESPUESTAS> TBL_POST_COMENTARIO_RESPUESTAS { get; set; }
        public virtual DbSet<TBL_POST_COMENTARIOS> TBL_POST_COMENTARIOS { get; set; }
        public virtual DbSet<TBL_POSTS> TBL_POSTS { get; set; }
        public virtual DbSet<TBL_POSTS_FAVORITOS> TBL_POSTS_FAVORITOS { get; set; }
        public virtual DbSet<TBL_PUBLICACION_COMENTARIO_RESPUESTAS> TBL_PUBLICACION_COMENTARIO_RESPUESTAS { get; set; }
        public virtual DbSet<TBL_PUBLICACION_COMENTARIOS> TBL_PUBLICACION_COMENTARIOS { get; set; }
        public virtual DbSet<TBL_PUBLICACIONES> TBL_PUBLICACIONES { get; set; }
        public virtual DbSet<TBL_RANGOS> TBL_RANGOS { get; set; }
        public virtual DbSet<TBL_USUARIOS> TBL_USUARIOS { get; set; }
        public virtual DbSet<TBL_USUARIOS_POSTS> TBL_USUARIOS_POSTS { get; set; }
    }
}
