//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReloadWS.DAL.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CATEGORIAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_CATEGORIAS()
        {
            this.TBL_POSTS = new HashSet<TBL_POSTS>();
        }
    
        public int CATEGORIAid { get; set; }
        public string CATEGORIA_NOMBRE { get; set; }
        public string CATEGORIA_LOGO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_POSTS> TBL_POSTS { get; set; }
    }
}
