//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReloadWS.DAL.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MENSAJE_RESPUESTAS
    {
        public int MENSAJE_RESPUESTA_ID { get; set; }
        public int MENSAJE_RESPUESTA_MENSAJE_ID { get; set; }
        public string MENSAJE_RESPUESTA_CONTENIDO { get; set; }
        public System.DateTime MENSAJE_RESPUESTA_FECALT { get; set; }
        public bool MENSAJE_RESPUESTA_DEBAJA { get; set; }
    
        public virtual TBL_MENSAJES TBL_MENSAJES { get; set; }
    }
}
