//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReloadWS.DAL.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USUARIOS_POSTS
    {
        public int USUARIO_POST_USUARIO_ID { get; set; }
        public int USUARIO_POST_POST_ID { get; set; }
        public bool USUARIO_POST_DEBAJA { get; set; }
    
        public virtual TBL_POSTS TBL_POSTS { get; set; }
        public virtual TBL_USUARIOS TBL_USUARIOS { get; set; }
    }
}
