//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReloadWS.DAL.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MENSAJES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MENSAJES()
        {
            this.TBL_MENSAJE_RESPUESTAS = new HashSet<TBL_MENSAJE_RESPUESTAS>();
        }
    
        public int MENSAJEid { get; set; }
        public string MENSAJE_ASUNTO { get; set; }
        public string MENSAJE_CONTENIDO { get; set; }
        public int MENSAJE_EMISOR { get; set; }
        public int MENSAJE_RECEPTOR { get; set; }
        public System.DateTime MENSAJE_FECALT { get; set; }
        public bool MENSAJE_DEBAJA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MENSAJE_RESPUESTAS> TBL_MENSAJE_RESPUESTAS { get; set; }
        public virtual TBL_USUARIOS TBL_USUARIOS { get; set; }
        public virtual TBL_USUARIOS TBL_USUARIOS1 { get; set; }
    }
}
