//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReloadWS.DAL.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PUBLICACIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_PUBLICACIONES()
        {
            this.TBL_PUBLICACION_COMENTARIOS = new HashSet<TBL_PUBLICACION_COMENTARIOS>();
        }
    
        public int PUBLICACIONid { get; set; }
        public int PUBLICACION_USUARIOid { get; set; }
        public string PUBLICACION_CONTENIDO { get; set; }
        public int PUBLICACION_POS { get; set; }
        public int PUBLICACION_NEG { get; set; }
        public System.DateTime PUBLICACION_FECALT { get; set; }
        public System.DateTime PUBLICACION_FECMOD { get; set; }
        public bool PUBLICACION_DEBAJA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PUBLICACION_COMENTARIOS> TBL_PUBLICACION_COMENTARIOS { get; set; }
        public virtual TBL_USUARIOS TBL_USUARIOS { get; set; }
    }
}
