//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReloadWS.DAL.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_POST_COMENTARIO_RESPUESTAS
    {
        public int POST_COMENTARIO_RESPUESTAid { get; set; }
        public int POST_COMENTARIO_RESPUESTA_COMENTARIOid { get; set; }
        public int POST_COMENTARIO_RESPUESTA_USUARIOid { get; set; }
        public string POST_COMENTARIO_RESPUESTA_CONTENIDO { get; set; }
        public int POST_COMENTARIO_RESPUESTA_POS { get; set; }
        public int POST_COMENTARIO_RESPUESTA_NEG { get; set; }
        public bool POST_COMENTARIO_DEBAJA { get; set; }
        public System.DateTime POST_COMENTARIO_FECALT { get; set; }
    
        public virtual TBL_POST_COMENTARIOS TBL_POST_COMENTARIOS { get; set; }
        public virtual TBL_USUARIOS TBL_USUARIOS { get; set; }
    }
}
