//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReloadWS.DAL.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PUBLICACION_COMENTARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_PUBLICACION_COMENTARIOS()
        {
            this.TBL_PUBLICACION_COMENTARIO_RESPUESTAS = new HashSet<TBL_PUBLICACION_COMENTARIO_RESPUESTAS>();
        }
    
        public int PUBLICACION_COMENTARIO_ID { get; set; }
        public int PUBLICACION_COMENTARIO_PUBLICACION_ID { get; set; }
        public int PUBLICACION_COMENTARIO_USUARIO_ID { get; set; }
        public string PUBLICACION_CONTENIDO { get; set; }
        public int PUBLICACION_POS { get; set; }
        public int PUBLICACION_NEG { get; set; }
        public System.DateTime PUBLICACION_FECALT { get; set; }
        public bool PUBLICACION_DEBAJA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PUBLICACION_COMENTARIO_RESPUESTAS> TBL_PUBLICACION_COMENTARIO_RESPUESTAS { get; set; }
        public virtual TBL_PUBLICACIONES TBL_PUBLICACIONES { get; set; }
        public virtual TBL_USUARIOS TBL_USUARIOS { get; set; }
    }
}
