//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReloadWS.DAL.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_POST_COMENTARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_POST_COMENTARIOS()
        {
            this.TBL_POST_COMENTARIO_RESPUESTAS = new HashSet<TBL_POST_COMENTARIO_RESPUESTAS>();
        }
    
        public int POST_COMENTARIO_ID { get; set; }
        public int POST_COMENTARIO_USUARIO_ID { get; set; }
        public int POST_COMENTARIO_POST_ID { get; set; }
        public string POST_COMENTARIO_CONTENIDO { get; set; }
        public System.DateTime POST_COMENTARIO_FECALT { get; set; }
        public bool POST_COMENTARIO_DEBAJA { get; set; }
        public int POST_COMENTARIO_POS { get; set; }
        public int POST_COMENTARIO_NEG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_POST_COMENTARIO_RESPUESTAS> TBL_POST_COMENTARIO_RESPUESTAS { get; set; }
        public virtual TBL_POSTS TBL_POSTS { get; set; }
        public virtual TBL_USUARIOS TBL_USUARIOS { get; set; }
    }
}
