//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReloadWS.DAL.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_POSTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_POSTS()
        {
            this.TBL_POST_COMENTARIOS = new HashSet<TBL_POST_COMENTARIOS>();
            this.TBL_POSTS_FAVORITOS = new HashSet<TBL_POSTS_FAVORITOS>();
            this.TBL_USUARIOS_POSTS = new HashSet<TBL_USUARIOS_POSTS>();
        }
    
        public int POST_ID { get; set; }
        public int POST_CANT_COMENTARIOS { get; set; }
        public int POST_PROPIETARIO { get; set; }
        public string POST_TITULO { get; set; }
        public string POST_COTENIDO { get; set; }
        public string POST_CONTENIDO_EDIT { get; set; }
        public string POST_TAGS { get; set; }
        public int POST_PUNTOS { get; set; }
        public int POST_VISITAS { get; set; }
        public bool POST_STICKY { get; set; }
        public int POST_CATEGORIA { get; set; }
        public int POST_SEGUIDORES { get; set; }
        public int POST_FAVORITOS { get; set; }
        public System.DateTime POST_FECALT { get; set; }
        public System.DateTime POST_FECMOD { get; set; }
        public bool POST_SE_COMENTA { get; set; }
        public bool POST_DEBAJA { get; set; }
        public string POST_IMAGEN { get; set; }
    
        public virtual TBL_CATEGORIAS TBL_CATEGORIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_POST_COMENTARIOS> TBL_POST_COMENTARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_POSTS_FAVORITOS> TBL_POSTS_FAVORITOS { get; set; }
        public virtual TBL_USUARIOS TBL_USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_USUARIOS_POSTS> TBL_USUARIOS_POSTS { get; set; }
    }
}
