//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReloadWS.DAL.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RANGOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_RANGOS()
        {
            this.TBL_USUARIOS = new HashSet<TBL_USUARIOS>();
        }
    
        public int RANGO_ID { get; set; }
        public string RANGO_NOMBRE { get; set; }
        public string RANGO_DESCRP { get; set; }
        public string RANGO_IMAGEN { get; set; }
        public int RANGO_PUNTOS_REQ { get; set; }
        public int RANGO_PUNTOS_DAR { get; set; }
        public int RANGO_COMENTARIOS { get; set; }
        public bool RANGO_DEBAJA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_USUARIOS> TBL_USUARIOS { get; set; }
    }
}
