
CREATE TABLE TBL_POSTS(
	POST_ID INT IDENTITY(1,1) NOT NULL,
	POST_CANT_COMENTARIOS INT NOT NULL DEFAULT 0,
	POST_PROPIETARIO INT NOT NULL,
	POST_TITULO VARCHAR(100) NOT NULL,
	POST_COTENIDO VARCHAR(MAX) NOT NULL,
	POST_CONTENIDO_EDIT VARCHAR(MAX) NOT NULL,
	POST_TAGS VARCHAR(200) NOT NULL,
	POST_PUNTOS INT NOT NULL DEFAULT 0,
	POST_VISITAS INT NOT NULL DEFAULT 0,
	POST_STICKY BIT NOT NULL DEFAULT 0,
	POST_CATEGORIA INT NOT NULL,
	POST_SEGUIDORES INT NOT NULL DEFAULT 0,
	POST_FAVORITOS INT NOT NULL DEFAULT 0,
	POST_FECALT DATETIME NOT NULL DEFAULT GETDATE(),
	POST_FECMOD DATETIME NOT NULL DEFAULT GETDATE(),
	POST_SE_COMENTA BIT NOT NULL DEFAULT 1,
	POST_DEBAJA BIT NOT NULL DEFAULT 0,
	CONSTRAINT PK_TBL_POSTS PRIMARY KEY(POST_ID),
	CONSTRAINT FK_TBL_POSTS_PROP FOREIGN KEY(POST_PROPIETARIO) REFERENCES TBL_USUARIOS(USUARIO_ID),
	CONSTRAINT FK_TBL_POSTS_CAT FOREIGN KEY(POST_CATEGORIA) REFERENCES TBL_CATEGORIAS(CATEGORIA_ID)
)

SP_HELP TBL_USUARIOS


CREATE TABLE TBL_USUARIOS_POSTS(
	USUARIO_POST_USUARIO_ID INT NOT NULL,
	USUARIO_POST_POST_ID INT NOT NULL,
	USUARIO_POST_DEBAJA BIT NOT NULL DEFAULT 0,
	CONSTRAINT PK_TBL_USUARIOS_POST PRIMARY KEY(USUARIO_POST_USUARIO_ID, USUARIO_POST_POST_ID),
	CONSTRAINT FK_TBL_USUARIO_POST_USUARIO FOREIGN KEY(USUARIO_POST_USUARIO_ID) REFERENCES TBL_USUARIOS(USUARIO_ID),
	CONSTRAINT FK_TBL_USUARIO_POST_POST FOREIGN KEY(USUARIO_POST_POST_ID) REFERENCES TBL_POSTS(POST_ID)

)

CREATE TABLE TBL_POST_COMENTARIOS(
	POST_COMENTARIO_ID INT IDENTITY(1,1) NOT NULL,
	POST_COMENTARIO_USUARIO_ID INT NOT NULL,
	POST_COMENTARIO_POST_ID INT NOT NULL,
	POST_COMENTARIO_CONTENIDO VARCHAR(MAX) NOT NULL,
	POST_COMENTARIO_FECALT DATETIME NOT NULL DEFAULT GETDATE(),
	POST_COMENTARIO_DEBAJA BIT NOT NULL DEFAULT 0,
	POST_COMENTARIO_POS INT NOT NULL DEFAULT 0,
	POST_COMENTARIO_NEG INT NOT NULL DEFAULT 0,
	CONSTRAINT PK_TBL_POST_COMENTARIOS PRIMARY KEY(POST_COMENTARIO_ID),
	CONSTRAINT FK_TBL_POST_COMENTARIO_USUARIO FOREIGN KEY(POST_COMENTARIO_USUARIO_ID) REFERENCES TBL_USUARIOS(USUARIO_ID),
	CONSTRAINT FK_TBL_POST_COMENTARIO_POST FOREIGN KEY(POST_COMENTARIO_POST_ID) REFERENCES TBL_POSTS(POST_ID)
	
)

CREATE TABLE TBL_MENSAJES(
	MENSAJE_ID INT IDENTITY(1,1) PRIMARY KEY,
	MENSAJE_ASUNTO VARCHAR(300) NOT NULL,
	MENSAJE_CONTENIDO VARCHAR(MAX) NOT NULL,
	MENSAJE_EMISOR INT NOT NULL,
	MENSAJE_RECEPTOR INT NOT NULL,
	MENSAJE_FECALT DATETIME NOT NULL DEFAULT GETDATE(),
	MENSAJE_DEBAJA BIT NOT NULL DEFAULT 0,
	CONSTRAINT FK_TBL_MENSAJES_EMISOR FOREIGN KEY(MENSAJE_EMISOR) REFERENCES TBL_USUARIOS(USUARIO_ID),
	CONSTRAINT FK_TBL_MENSAJES_RECEPTOR FOREIGN KEY(MENSAJE_RECEPTOR) REFERENCES TBL_USUARIOS(USUARIO_ID)

)

CREATE TABLE TBL_PUBLICACIONES(
	PUBLICACION_ID INT IDENTITY(1,1) NOT NULL,
	PUBLICACION_USUARIO_ID INT NOT NULL,
	PUBLICACION_CONTENIDO VARCHAR(MAX),
	PUBLICACION_POS INT NOT NULL DEFAULT 0,
	PUBLICACION_NEG INT NOT NULL DEFAULT 0,
	PUBLICACION_FECALT DATETIME NOT NULL DEFAULT GETDATE(),
	PUBLICACION_FECMOD DATETIME NOT NULL DEFAULT GETDATE(),
	PUBLICACION_DEBAJA BIT NOT NULL DEFAULT 0,
	CONSTRAINT PK_TBL_PUBLICACIONES PRIMARY KEY(PUBLICACION_ID),
	CONSTRAINT FK_TBL_PUBLICACIONES_USUARIO FOREIGN KEY(PUBLICACION_USUARIO_ID) REFERENCES TBL_USUARIOS(USUARIO_ID)

)



CREATE TABLE TBL_PUBLICACION_COMENTARIOS(
	PUBLICACION_COMENTARIO_ID INT IDENTITY(1,1) PRIMARY KEY,
	PUBLICACION_COMENTARIO_PUBLICACION_ID INT NOT NULL,
	PUBLICACION_COMENTARIO_USUARIO_ID INT NOT NULL,
	PUBLICACION_CONTENIDO VARCHAR(MAX) NOT NULL,
	PUBLICACION_POS INT NOT NULL DEFAULT 0,
	PUBLICACION_NEG INT NOT NULL DEFAULT 0,
	PUBLICACION_FECALT DATETIME NOT NULL DEFAULT GETDATE(),
	PUBLICACION_DEBAJA BIT NOT NULL DEFAULT 0,
	CONSTRAINT FK_TBL_PUBLICACION_COMENTARIOS_PUBLICACION FOREIGN KEY(PUBLICACION_COMENTARIO_PUBLICACION_ID)
	REFERENCES TBL_PUBLICACIONES(PUBLICACION_ID),
	CONSTRAINT FK_TBL_PUBLICACION_USUARIO FOREIGN KEY(PUBLICACION_COMENTARIO_USUARIO_ID) REFERENCES TBL_USUARIOS(USUARIO_ID)


)

CREATE TABLE TBL_PUBLICACION_COMENTARIO_RESPUESTAS(
	PUBLICACION_COMENTARIO_RESPUESTAS_ID INT IDENTITY(1,1) PRIMARY KEY,
	PUBLICACION_COMENTARIO_RESPUESTA_COMENTARIO_ID INT NOT NULL,
	PUBLICACION_COMENTARIO_RESPUESTA_USUARIO_ID INT NOT NULL,
	PUBLICACION_COMENTARIO_RESPUESTA_CONTENIDO VARCHAR(MAX) NOT NULL,
	PUBLICACION_COMENTARIO_RESPUESTA_FECALT DATETIME NOT NULL DEFAULT GETDATE(),
	PUBLICACION_COMENTARIO_RESPUESTA_DEBAJA BIT NOT NULL DEFAULT 0,
	CONSTRAINT FK_TBL_PUBLICACION_COMENTARIO_RESPUESTA_COMENTARIO FOREIGN KEY(PUBLICACION_COMENTARIO_RESPUESTA_COMENTARIO_ID)
	REFERENCES TBL_PUBLICACION_COMENTARIOS(PUBLICACION_COMENTARIO_ID),
	CONSTRAINT FK_TBL_PUBLICACION_COMENTARIO_RESPUESTA_USUARIO FOREIGN KEY(PUBLICACION_COMENTARIO_RESPUESTA_USUARIO_ID)
	REFERENCES TBL_USUARIOS(USUARIO_ID)

)